# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58c6f07c66e6cd2bffad5469352f5164301a5aea5073a145df5c167793530b4b18268660428ab394ed0e1f236ce2d1678b6f9d698f8a7c19513b507d1baf9a42

test:
  secret_key_base: 8fcbe8655186df9128db5a21cdfb22866e44a354bafded8a97aa779e6ffa267ab5b64a8fe2ff1c6c7dc4af5851e2f7cbc737397b5e9f82f9b353113d5826badd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
